### ISSUE TITLE
Please add  possibility to choose which tool to use to open file in browser.

### ISSUE THREAD

**Issue by faridsaid20** [isak102/telescope-git-file-history.nvim#2]
I use wsl and other tools are higher up in the chain

something like this would be good?

![image](https://github.com/isak102/telescope-git-file-history.nvim/assets/119894088/b0f50bc2-0f6d-44c7-9055-914f6d802c2c)

**Comment by isak102** [comment]
Good idea! Added a `browser_command` configuration option

https://github.com/isak102/telescope-git-file-history.nvim?tab=readme-ov-file#configuration
