### ISSUE TITLE
Clear new line for url

### ISSUE THREAD

**Issue by faridsaid20** [isak102/telescope-git-file-history.nvim#6]
Not sure if it's only for me, but the get_repo_url returns url with a new line char at the end.
It prevents the url to be opened...
I get the same with github and azure urls.

Would be amazing to remove new line at the end of repo url.

![image](https://github.com/isak102/telescope-git-file-history.nvim/assets/119894088/dd75d054-83e8-443c-afb8-8440ec43fb53)

**Comment by tom-on-the-internet** [comment]
I have the same issue. Thank you for pointing out what it is.
really enjoying this extension

**Comment by isak102** [comment]
Interesting, doesn't happen for me. Should be fixed now
